FROM ros:melodic
RUN apt-get update && apt-get -y upgrade
RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"
COPY  ./src /auto_car/src
RUN apt-get install -y ros-melodic-serial  ros-melodic-tf ros-melodic-urdf ros-melodic-diagnostic-updater   ros-melodic-tf2-geometry-msgs  ros-melodic-bfl \
    ros-melodic-angles ros-melodic-cv-bridge ros-melodic-image-transport  ros-melodic-joy ros-melodic-xacro ros-melodic-laser-geometry ros-melodic-map-msgs \
    ros-melodic-tf2-sensor-msgs ros-melodic-move-base-msgs ros-melodic-costmap-converter ros-melodic-mbf-costmap-core ros-melodic-interactive-markers \
    ros-melodic-mbf-msgs ros-melodic-tf2-eigen ros-melodic-libg2o ros-melodic-ecl-threads
RUN apt-get install -y libbullet-dev libsdl-dev  libsdl-image1.2-dev libyaml-cpp-dev liborocos-bfl-dev libopencv-dev libcv-bridge-dev libsuitesparse-dev 
RUN cd /auto_car/src && catkin_make
    